apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  namespace: monitoring
  labels:
    release: monitoring  
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}  
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: {{ .Values.service.name }}  
      path: /metrics  
      interval: 15s  
      scrapeTimeout: 14s  
