name: Deploy to Docker Hub

on:
  push:
    paths-ignore:
      - 'Maya-Kind-Manifest/**'
      - '**.md'
      
env:
  REPOSITORY: ${{ secrets.DOCKERHUB_USERNAME }}/maya-repo
  BRANCH_NAME: ${{ github.ref_name }}


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ env.BRANCH_NAME }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      working-directory: ./app
      run: |
        docker build -t ${{ env.REPOSITORY }}:0.1.${{ github.run_number }} .
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REPOSITORY }}:0.1.${{ github.run_number }}
        format: 'json'
        output: 'trivy-results.json'

    - name: Push Trivy scan results
      uses: actions/upload-artifact@v4
      with:
        name: trivy-results
        path: trivy-results.json

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PAT }}

    - name: Push Docker image
      run: docker push ${{ env.REPOSITORY }}:0.1.${{ github.run_number }}